### ISSUE TITLE
No support for .au tld

### ISSUE THREAD

**Issue by NotACoward** [DannyCork/python-whois#122]
Can you please add support for the .au tld? 
The whois server is whois.audns.net.au

Thanks :)

**Comment by PeterStavrou** [comment]
This has been fixed by Xanish though I don't think the package has been updated.
Follow the below steps:

1. Copy the code from:
https://raw.githubusercontent.com/xanish/python-whois/master/whois/tld_regexpr.py

2. Into where ever your package is located:
\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\whois\tld_regexpr.py

Then it will work.

Hopefully his solution gets updated into the official package.

**Comment by DannyCork** [comment]
au is supported
