### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by IR0DayToday** [DannyCork/python-whois#181]
return the none !!!

**Comment by IR0DayToday** [comment]
im use python 3.8

# code : 
import whois

w = whois.query("google.com")

print(w)
result : 
none

===================================
# Code ; 
import whois

w = whois.query("google.com")

print(w.__dict__)

result :
Traceback (most recent call last):
  File "c:\Users\X0P4SH4\Desktop\py\T00L\tempCodeRunnerFile.python", line 5, in <module>
    print(w.__dict__)
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by tpavesi** [comment]
same for me

**Comment by tpavesi** [comment]
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> domain = whois.query('google.com')
>>> print(domain.__dict__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by StalKlim** [comment]
With the same code as above, but on version 3.9.9 I get the following:
`Traceback (most recent call last):
  File "c:\Users\stalv\Desktop\whois.py", line 1, in <module>
    import whois
  File "c:\Users\stalv\Desktop\whois.py", line 3, in <module>
    w = whois.query("google.com")
AttributeError: partially initialized module 'whois' has no attribute 'query' (most likely due to a circular import)`

Code:
`import whois

w = whois.query("google.com")

print(w.dict)`

**Comment by DannyCork** [comment]
```
import whois

w = whois.query("google.com")
print(w.__dict__)
```

works.
