### ISSUE TITLE
pl domains sometimes return null

### ISSUE THREAD

**Issue by ZurisW** [DannyCork/python-whois#208]
## Describe the bug
PL domains like wp.pl sometimes return null instead of whois data like domain name, registar etc. It always works for .com.
I know for sure it works for pl domains but rarely as I got the results multiple times

## To Reproduce
Just py code below, but it seems its random?
w = whois.whois("wp.pl")
print(w)

## Expected behavior
whois returns data

**Comment by maarten-boot** [comment]
limiting frequently causes this issue, please try again with the new code 
(please download the code manually until the next python lib is published)
the new code tries to detect many strings indicating query limits and raises a specific exception:

 * whois.WhoisQuotaExceeded

see: https://www.dns.pl/en/whois/FAQ

Is WHOIS querying limited?

Yes. The WHOIS database is protected against systematic querying in order to obtain data which, in turn, may leave room for abuse.

The number of responses to WHOIS queries is limited per a particular IP address in a specific unit of time.

The administrators of the .pl domain Registry may block the traffic from any IP address if a suspicious action has been observed (e.g. attempts of massive querying).
