### ISSUE TITLE
.za TLD is not allowed to be registered

### ISSUE THREAD

**Issue by zeocax** [DannyCork/python-whois#248]
Some SLDs are allowed as listed:

https://registry.net.za/content.php?gen=1&contentid=171&title=Port+43+WHOIS+Service

**Comment by maarten-boot** [comment]
Of course 'za' tld is allowed to be registered 
otherwise the domain nsza.is.co.za would not exist 
valid tld's should always be verified against https://www.iana.org/domains/root/db and 
can be programatically validated with: https://pypi.org/project/tld/
Note that tld's are only added when the whois parsing of the data returned is known. 
Feel free to contribute

**Comment by maarten-boot** [comment]
i have added the 4 valid subdomains of za in my last pull req: https://github.com/DannyCork/python-whois/pull/247

**Comment by zeocax** [comment]
> Of course 'za' tld is allowed to be registered otherwise the domain nsza.is.co.za would not exist valid tld's should always be verified against https://www.iana.org/domains/root/db and can be programatically validated with: https://pypi.org/project/tld/ Note that tld's are only added when the whois parsing of the data returned is known. Feel free to contribute

My fault, I mean the ".za top-domain" is not allowed. I know some of its subdomains is valid as this page shows: https://registry.net.za/content.php?gen=1&contentid=171&title=Port+43+WHOIS+Service (with .CAPETOWN, .DURBAN, .JOBURG)

**Comment by DannyCork** [comment]
merged
